### ISSUE TITLE
Merkle tree for proof of assets

### ISSUE THREAD

**Issue by alxkzmn** [summa-dev/summa-solvency#10]
## Zero-Knowledge Proof of Assets

It is necessary for the exchange to prove the ownership of its *m* addresses whose balances sum up to an amount greater than or equal to the total liabilities *L*:

*∑(bal<sub>1..m</sub>) >= L*

The exchange wants to hide its addresses in the anonymity set of top-holding *n* addresses. [The straightforward approach](https://youtu.be/ChX8MuRVzmw?t=1293) is to provide an array of *n* addresses and balances as a public input and binary indices and signatures as a private input to select the *m* addresses for a signature check and a summation. A reasonably big anonymity set is *[n = 2<sup>14</sup>](https://youtu.be/ChX8MuRVzmw?t=1301) = 16384*, but an input array of such size is challenging to use for a zero-knowledge proof. Instead, it is possible to use a Merkle tree and significantly reduce the number of inputs to the circuit.

Let's assume that *m << n*, e.g., [the exchange owns fewer than a 100 addresses](https://etherscan.io/accounts/label/binance) out of 16384. This will allow to create a circuit with fixed number of inputs that is relatively small but enough to handle the possible *m*, e.g., 100 inputs. The unused inputs will be stuffed with dummy values. It is then possible to prove the ownership and the total stored amount by providing:

* Merkle tree root (publicly known) for all *n* addresses where leaves of the tree are pairs of (address, balance);
* Merkle path indices to the owned *m* (addresses+balances) (and *100 - m* dummy ones) - array of 14 elements (tree height is 14): *100 x 14 = 1400* inputs (or even fewer if treated as a 14-bit binary number);
* Merkle path elements to the owned *m* addresses (and *100 - m* dummy ones). It makes sense to always provide all the top 7 level elements for the tree as a separate input because *m = 100 ~= 2<sup>7</sup>* and if the *m* exchange addresses are evenly spread among the *n* tree leaves, their Merkle paths will go through almost all the nodes of the top 7 levels. This way, the number of inputs for the remaining path elements will be *100 x (14-7) = 700*
* *m* signatures (and *100 - m* dummy ones) - 100 in total.

### Address array approach:

16384 addresses + 16384 signatures (including dummy ones) + 16384 balances + array index = at least **49152** + some overhead depending on how the array index is encoded.

### Merkle tree approach:

1 root + 254 "shared" top 7 level path elements + 700 "varying" lower path elements + 1400 (or 100) path indices + 100 signatures = **2455 (2355)**

The **downside** of the MT approach is that it requires **extra hashing** operations to prove the inclusion of an address.

## Development Notes

Put the circuit here:
https://github.com/summa-dev/circuits-halo2/tree/master/src/circuits
Reference Merkle tree implementations are here:
https://github.com/summa-dev/halo2-experiments#experiment-8---merkle-tree-v3

**Comment by alxkzmn** [comment]
@enricobottazzi should we close this?

**Comment by enricobottazzi** [comment]
yes
