### ISSUE TITLE
fix `get_params` function

### ISSUE THREAD

**Issue by enricobottazzi** [summa-dev/summa-solvency#100]
Right now we have a `get_params` function inside the backend and a `generate_setup_params` inside zk_prover/utils.

The two functions perform the same action. The only difference is that the first fetches the parameters from a file while the second can generate the params using a random setup. 

I propose to unify it in a single function that takes a input `k` and an Option `path`. If the path is supplied, it generates the `params` using the setup. If the `path` is not supplied, it generates the params starting from a random factor

**Comment by sifnoc** [comment]
> Right now we have a `get_params` function inside the backend and a `generate_setup_params` inside zk_prover/utils.

Do you mean this function?
https://github.com/summa-dev/summa-solvency/blob/ded7155c585eabef653bfc84ec26ca10a6acd632/backend/src/apis/utils.rs#L14

**Comment by sifnoc** [comment]
the `generate_setup_param` function is used in many places, benches and tests. So, It would be beneficial to move `generate_setup_artifacts` into `zk_prover/src/circuit/utils` and remove duplicate logic like the one below.

```Rust
pub fn generate_setup_artifacts<C: Circuit<Fp> + CircuitExt<Fp>>(
    params_path: &str,
    k: u32,
    circuit: C,
) -> Result<SetupArtifats, &'static str> {
    let template_params = generate_setup_params(k, Some(params_path.to_string()));

    let mut params = template_params;

    if params.k() < k {
        return Err("k is too large for the given params");
    }

    if params.k() > k {
        params.downsize(k);
    }

    let vk = keygen_vk(&params, &circuit).expect("vk generation should not fail");
    let pk = keygen_pk(&params, vk.clone(), &circuit).expect("pk generation should not fail");

    Ok((params, pk, vk))
}
``` 

What do you think?

**Comment by enricobottazzi** [comment]
I prefer the logic of the current `generate_setup_artifacts` compared to the `generate_setup_params` function.

I think we can replace `generate_setup_params` with `generate_setup_artifacts` everywhere (tests and benches).  

I would just propose to modify `generate_setup_artifacts` to take the `params_path` as an option. It it finds a valid params path, the artifacts are generated using this trusted setup. If no `params_path` is provided, a random trusted setup is generated (similarly to how `generate_setup_params` works currently)
