### ISSUE TITLE
Support more than 64 bits in Circuit

### ISSUE THREAD

**Issue by enricobottazzi** [summa-dev/summa-solvency#107]
As of now, the circuits are tuned to support balances within the 64 bits range. That's because there's an overflow check in place that fails the proof generation if a balance exceeds this range. Ideally, this range should be increased at least to the double of it. 

The reason to limiting it to 64 range was because an higher range would make the proof too big to verify on-chain

This can be achieved either:

- Adding a more efficient Solidity Verifier from EZKL
- Reducing the offsets in the LTChip as mentioned in #91

**Comment by ameya-deshmukh** [comment]
@enricobottazzi can I take this? :)

**Comment by enricobottazzi** [comment]
hey @ameya-deshmukh

Sure. This is pretty crucial for us! The goal would be to accept balances in the range of 248 BITS, which is the max range multiple of 8 within the finite field.

I suggest starting by applying the new solidity verifier from https://github.com/summa-dev/summa-solvency/blob/master/zk_prover/src/circuits/utils.rs#L113-L114 and see in tests how much you can increase `N_BYTES` and pass `test_solvency_on_chain_verifier`. This can already be a PR.

A second PR can be the work on making the `LTChip` more efficient! 

LMK
