### ISSUE TITLE
Add whole flow example to backend examples

### ISSUE THREAD

**Issue by enricobottazzi** [summa-dev/summa-solvency#128]
It would be cool to add the whole flow to `backend/examples`

It should involve: 

- Message signatures to build `csv` file.
- Snapshot generation 
- Proof of Address ownership generation and submission to smart contract 
- Proof of Solvency generation and submission to smart contract 
- Proof of Mst Inclusion generation 
- Proof of Mst Inclusion verification (user side)

Ideally, the example should contain as few lines of code as possible, as all these actions should be abstracted by the backend APIs. This exercise can also inform a better design of the APIs if needed.

**Comment by enricobottazzi** [comment]
@sifnoc after #152 is merged

I guess that according to the modification we can provide in the example both 

- Proof of Mst Inclusion Verification (user side - performed locally using the Verification Key)
- Proof of Mst Inclusion Verification (user side - performed interacting with the view function of the Summa Smart Contract)

**Comment by sifnoc** [comment]
Related `Message signatures to build csv file.` task, Ensure that the Ethereum addresses in the file adhere to the checksum format

**Comment by enricobottazzi** [comment]
https://github.com/summa-dev/summa-solvency/pull/152#discussion_r1319703249

I think that the new example flow will just need to interact with `AddressOwnership` and `Round` objects. Therefore we can make the `Snapshot` struct as private.

**Comment by sifnoc** [comment]
- [x] Message signatures to build `csv` file.
- [ ] ~~Snapshot generation~~
- [x] Proof of Address ownership generation and submission to smart contract 
- [x] Proof of Solvency generation and submission to smart contract
- [ ] Proof of Mst Inclusion verification (user side - locally using given Verification Key)
- [ ] Proof of Mst Inclusion Verification (user side - performed interacting with the view function of the Summa Smart Contract)
