### ISSUE TITLE
More efficient `Range Check` implementation 

### ISSUE THREAD

**Issue by enricobottazzi** [summa-dev/summa-solvency#130]
The goal of the range check chip is to evaluate that a value is within the required range determined by `N_BYTES`

As mentioned in #77, the goal is to improve the performance of the range check chip such that it accomplishes the same goal by performing fewer relative rotations.

The proposed implementation can be found at => https://github.com/enricobottazzi/scaffold-halo2

The logic is the following:

This helper checks that the value witnessed in a given cell is within a given range defined by N_BYTES. We consider the example in which we want to check that `value` `0x1f2f3f4f` is in a range `N_BYTES=4` 

 |     | value      | decomposed_value | running_sum | toggle_running_sum_check | toggle_lookup_check |
 | --- | ---------- | ---------------- | ----------- | ------------------------ | ------------------- |
 | 0   | -          | -                | 0x00        | 0                        | 0                   |
 | 1   | 0x1f2f3f4f | 0x1f             | 0x1f        | 1                        | 1                   |
 | 2   |            | 0x2f             | 0x1f2f      | 1                        | 1                   |
 | 3   |            | 0x3f             | 0x1f2f3f    | 1                        | 1                   |
 | 4   |            | 0x4f             | 0x1f2f3f4f  | 1                        | 1                   |

The column decomposed_value contains the decomposed value of `value` in #N_BYTES byte chunks, big-endian.
The column running_sum contains the running sum of the values in decomposed_value. In particular the running_sum in a particular row is the result of concatenating the prev running_sum with the current decomposed_value.
The contraints that are enforced are:
 - `(running_sum(prev) << 8) + decomposed_value(cur) = running_sum(cur)` (enable by toggle_running_sum_check)
 - `decomposed_value(cur) ∈ u8_lookup_table` (enable by toggle_lookup_check)
 - `value(1) == running_sum(4)` (copy constraint applied here)

With the proposed implementation, the maximum relative rotation performed when setting the constraints equals -1.

Let's consider the case of a value `0x1f2f3f4f5f6f7f8f` that overflow the required range of `N_BYTES=4`.  This would be the behaviour:

|     | value               | decomposed_value    | running_sum              | toggle_running_sum_check | toggle_lookup_check |
|-----|-------------        |------               |------                    | ------                   | ------              |
|  0  |  -                  | -                   | 0x00                     | 0                        | 0                   |
|  1  | 0x1f2f3f4f5f6f7f8f  | 0x1f                | 0x1f                     | 1                        | 1                   |
|  2  |                     | 0x2f                | 0x1f2f                   | 1                        | 1                   |
|  3  |                     | 0x3f                | 0x1f2f3f                 | 1                        | 1                   |
|  4  |                     | 0x4f                | 0x1f2f3f4f5f6f7f8f       | 1                        | 1                   |
    
     The constraint => (running_sum(prev) << 8) + decomposed_value(cur) = running_sum(cur) should fail at offset 4

@alxkzmn, @sifnoc, I'm wondering what's your opinion on that and if you see any security issue before creating a PR and applying it to Summa. Is there any missing constraint?

**Comment by sifnoc** [comment]
We have to make sure `running_sum(0)` is zero.

**Comment by sifnoc** [comment]
I've been thinking about this for a while: What if the utility functions, such as `big_uint_to_8bit_chunks` and `running_sums_of_chunks`, are manipulated? Could it lead to avoiding the constraints, like the one below?

 |     | value      | decomposed_value | running_sum | toggle_running_sum_check | toggle_lookup_check |
 | --- | ---------- | ---------------- | ----------- | ------------------------ | ------------------- |
 | 0   | -          | -                | 0x0       | 0                        | 0                   |
 | 1   | 0xff2f3f4f | 0x0            | 0x0        | 1                        | 1                   |
 | 2   |            | 0x0             | 0x0      | 1                        | 1                   |
 | 3   |            | 0x0             | 0xff2f3f    | 1                        | 1                   |
 | 4   |            | 0x4f             | 0xff2f3f4f  | 1                        | 1                   |

**Comment by enricobottazzi** [comment]
Hi @sifnoc, yes I think you are right in both cases!

**Comment by sifnoc** [comment]
I thought it would work, but it's not

A table for an alternative approach without selectors
| value      	| exclude_decomposed_value 	| decomposed_value 	|
|------------	|--------------------------	|------------------	|
| 0x1f2f3f4f 	| 0x2f3f4f                 	| 0x1f             	|
| 0x1f2f3f4f 	| 0x1f003f4f               	| 0x2f             	|
| 0x1f2f3f4f 	| 0x1f2f004f               	| 0x3f             	|
| 0x1f2f3f4f 	| 0x1f23f00                	| 0x4f             	|

One of the constraints 
- `value == exclude_decomposed_value(cur) + ( decomposed_value(cur) << 8 * ((N_BYTES -1) - i) )`

**Comment by sifnoc** [comment]
Thanks! That clears things up for me!
So, to make sure I understand, `z(4) = (0x1f - 0x0) / 2^8`, right?

It's crucial to get 0 at `z_W`, the last element of `z`. But what if the prover just sets `N_BYTES` one higher than expected? It seems that this would always result in 0. For example, the modulus in `BN256` is:
For example, the modulus in BN256 is `[
            0x30, 0x64, 0x4e, 0x72, 0xe1, 0x31, 0xa0, 0x29, 0xb8, 0x50, 0x45, 0xb6, 0x81, 0x81,
            0x58, 0x5d, 0x28, 0x33, 0xe8, 0x48, 0x79, 0xb9, 0x70, 0x91, 0x43, 0xe1, 0xf5, 0x93,
            0xf0, 0x00, 0x00, 0x01,
        ];`, 32 elements. If the prover simply sets N_BYTES` as 33, it seems like it would allow an overflow, don't you think?"

**Comment by enricobottazzi** [comment]
Actually the expression `z(4) = (0x1f - 0x1f) / 2^8` seems correct to me according to this:

$$z_{i+1} = (z_{i} - k_i) / (2^K).$$

Where `z(3)` is the previous running sum and `k(3)` is the most significant decomposed byte.

Related to your second comment, I think this is a really good point. 

It seems that the only part in which `N_BYTES` takes part in the circuit key generation phase is here: 

https://github.com/summa-dev/summa-solvency/blob/437499c86ee423c77ec5eb33b8d1499a895903c8/zk_prover/src/chips/range/range_check.rs#L100-L103

Indeed, quoting CC 
"Some parts of the witness assignment functions go to the key generation function:
- As you said, copy constraints are in the key gen.
- All fixed columns and their assigned values are in the key gen.
- Selectors are fixed columns too. Their assigned values are in the key gen".

Since `N_BYTES` is assigned during key generation, also the values to `toogle_lookup_check` Selector column are assigned accordingly. 

Suppose the case in which `N_BYTES` is set to 4 during key generation. The malicious prover is trying to add a value `0xff1f2f3f4f` (which is not in the required range) to the witness table. 


 |     | z          |  toogle_lookup_check
 | --- | ---------- | ------ | 
 | 0   | 0xff1f2f3f4f| 1 |
 | 1   | 0xff1f2f3f  | 1 |
 | 2   | 0xff1f2f   | 1 | 
 | 3   | 0xff1f       |  1 | 
 | 4   | 0xff      | 0 |
 | 5   | 0x00       | 0 |

The constraint `z(cur) - 2^8⋅z(next) ∈ lookup_u8` will be satisfied for each row in which `toogle_lookup_check` is activated. 

The constraint `z(last) == 0` will also be satisfied. Note that this is not dependent for `N_BYTES`

https://github.com/summa-dev/summa-solvency/blob/437499c86ee423c77ec5eb33b8d1499a895903c8/zk_prover/src/chips/range/range_check.rs#L147.

What I noticed is that by adding

`println!("zs: {:?}", zs);` at the end of the loop 

and checking the configuration phase for the `RangeChip` by running `cargo test --release --features dev-graph -- --nocapture print_range_check_test`, this is what you get for a single Range Check

`
zs: [AssignedCell { value: Value { inner: None }, cell: Cell { region_index: RegionIndex(2), row_offset: 0, column: Column { index: 0, column_type: Advice } }, _marker: PhantomData<halo2curves::bn256::fr::Fr> }, AssignedCell { value: Value { inner: None }, cell: Cell { region_index: RegionIndex(2), row_offset: 1, column: Column { index: 0, column_type: Advice } }, _marker: PhantomData<halo2curves::bn256::fr::Fr> }, AssignedCell { value: Value { inner: None }, cell: Cell { region_index: RegionIndex(2), row_offset: 2, column: Column { index: 0, column_type: Advice } }, _marker: PhantomData<halo2curves::bn256::fr::Fr> }, AssignedCell { value: Value { inner: None }, cell: Cell { region_index: RegionIndex(2), row_offset: 3, column: Column { index: 0, column_type: Advice } }, _marker: PhantomData<halo2curves::bn256::fr::Fr> }, AssignedCell { value: Value { inner: None }, cell: Cell { region_index: RegionIndex(2), row_offset: 4, column: Column { index: 0, column_type: Advice } }, _marker: PhantomData<halo2curves::bn256::fr::Fr> }]
`

Which is indeed the correct configuration of 5 cells (as described in the previous comment) needed to perform the check on `N_BYTES = 4`. 

If this is not enough, one idea that I might have to add `N_BYTES` to the constraint is to replace #L147 with 

`region.constrain_constant(zs[N_BYTES].cell(), Fp::from(0))?;`

In such way we are replacing any last value of the vector `zs` to be zero.

**Comment by sifnoc** [comment]
Thanks for clarifying

> Suppose the case in which `N_BYTES` is set to 4 during key generation. The malicious prover is trying to add a value `0xff1f2f3f4f` (which is not in the required range) to the witness table.
> 
>  |     | z          |  toogle_lookup_check
>  | --- | ---------- | ------ | 
>  | 0   | 0xff1f2f3f4f| 1 |
>  | 1   | 0xff1f2f3f  | 1 |
>  | 2   | 0xff1f2f   | 1 | 
>  | 3   | 0xff1f       |  1 | 
>  | 4   | 0xff      | 0 |
>  | 5   | 0x00       | 0 |

> The constraint `z(cur) - 2^8⋅z(next) ∈ lookup_u8` will be satisfied for each row in which `toogle_lookup_check` is activated.
> 
> The constraint `z(last) == 0` will also be satisfied. Note that this is not dependent for `N_BYTES`

Is there a way the verifier can know what value is specified for `N_BYTES` in the circuit?

|   	|       z      	| n_bytes 	| toogle_lookup_check 	|
|:-:	|:------------:	|:-------:	|:-------------------:	|
| 0 	| 0xff1f2f3f4f 	| 4       	| 1                   	|
| 1 	| 0xff1f2f3f   	| 3       	| 1                   	|
| 2 	| 0xff1f2f     	| 2       	| 1                   	|
| 3 	| 0xff1f       	| 1       	| 1                   	|
| 4 	| 0xff         	| 0       	| 0                   	|
| 5 	| 0x00         	| 0       	| 0                   	|

I have a naive approach to prevent setting higher `N_BYTES` than expected. 

It involves adding `N_BYTES` to the public input too and adding one more constraint like `n_bytes(cur) = n_bytes(next) + 1`.

With this setup, the prover cannot cheat by setting N_BYTES higher than expected but it's bad for user experience.

**Comment by enricobottazzi** [comment]
> Is there a way the verifier can know what value is specified for `N_BYTES` in the circuit?

As far as I can tell, this info together with the ones related to constraints are encapsulated into the proving key and the verification key. A verifier can also tell the `N_BYTES` by instantiating the circuit with a specific `N_BYTES` value, running the setup and checking if the verification key is matching.

> I have a naive approach to prevent setting higher `N_BYTES` than expected.

That would work too. I will ask CC for a review on this if he's able to before moving any forward

**Comment by sifnoc** [comment]
That's great! Now we have three options for addressing this issue:

- Verifying the length of the `zs` from the given verification key (best).
- Generating a verification key with the specified `N_BYTES` from the given `ptau` file that is publicly known.
- Adding constraints for the `n_bytes` column in the range check circuit.

Can you open an issue for the first approach?

**Comment by enricobottazzi** [comment]
Actually the second approach that you are suggesting is what we are already doing in the latest commit at #132 

As the `MstInclusionCircuit` takes `N_BYTES` as generic input, the verification key has already this information encoded within it! 

https://github.com/summa-dev/summa-solvency/blob/943cd2c17568bbd807a6bc73a374ec64ba0fb0f2/zk_prover/src/circuits/merkle_sum_tree.rs#L29

**Comment by sifnoc** [comment]
I see. Let me describe this scenario from the user's perspective:

1. Verifying `N_BYTES` in the given verifying_key:
I envision that a user intending to verify a proof will receive `proof`, `setup_params`, and `verifying_key` files from the CEX. 
They will then verify the proof using a tool provided to them.
In this situation, the user needs to verify the `N_BYTES` in the `verifying_key` to ensure that the CEX has not engaged in any manipulation that might cause an overflow.
The total size of the key downloaded in this scenario is relatively smaller than the one generated from the specified circuit and `ptau` file.
(If it is not please let me know..)

2. Generating keys on the user side
Here, the user will only receive a `proof` file from the CEX, without any accompanying key files. The user must generate the `setup_params` and `verifying_key` by using the `ptau` file and specific parameters communicated by the CEX. 
This will allow the user to know the given parameter `N_BYTES`.

3. use `n_bytes` as public input
In this case, the user has to input `N_BYTES` for making instances. like `leaf_hash`.

So, the second approach is also acceptable to me. But ultimately, since N_BYTES is a sensitive parameter in the entire verification process, I believe the user has to learn how it is important.

**Comment by enricobottazzi** [comment]
Yes, these are the possible scenarios.

https://github.com/summa-dev/summa-solvency/blob/38997c85a7f4a3ce8dfc86b41e4ba500f0942c87/zk_prover/src/circuits/utils.rs#L80

The generation of the `vk` is a function of `circuit` and `params`. 

The user needs to check that the `vk` they receive from the CEX is the obtained by running such function using as `circuit` an instance of `MstInclusionCircuit` with the expected `N_BYTES`  and as `params` the one published by the CEX.

It might be too much of a hurdle to ask each user to perform this whole operation, but we should educate them about this potential attack vector by the CEX, which btw is not only limited to manipulating `N_BYTES` but any other constraint.

I think the scenario that I like the most is 1, with the possibility of verifying the correct generation of the `vk` being promoted as an optional check that the user can perform if they are extra cautious.
