### ISSUE TITLE
Add `ProofOfInclusion` Verifier view function inside the contract 

### ISSUE THREAD

**Issue by enricobottazzi** [summa-dev/summa-solvency#147]
It should take as input, proof, `username` and `balances[]` and the public inputs of the proof, namely `leaf_hash` and `root_hash`.

- Should verify the proof 
- Should verify that `H(username, balances[])` match `leaf_hash`
- Should verify that `root_hash` matches the one committed by the Exchange in `SubmitProofOfSolvency`

EDIT: maybe we should drop the second functionality and not pass `username` and `balances[]` as input at all. Even tough the function is not executed on chain, the user will likely use a third party node to perform such operation and therefore might not want to share these personal data

**Comment by alxkzmn** [comment]
I think it's better to keep the username and balances private.
