### ISSUE TITLE
Refactor signers

### ISSUE THREAD

**Issue by sifnoc** [summa-dev/summa-solvency#155]
- Relate the issue https://github.com/summa-dev/summa-solvency/issues/154
- Apply `NonceManager` in `ethers-rs` for this https://github.com/summa-dev/summa-solvency/pull/152#discussion_r1322866197
- More consideration with [Service-Based Backend Architecture](https://hackmd.io/CXoZfrc0Ri-UOd-whxvvnA)

**Comment by enricobottazzi** [comment]
- Separate Signer from `Round` and `AddressOwnership`
