### ISSUE TITLE
Integrate the univariate grand sum version with the backend

### ISSUE THREAD

**Issue by alxkzmn** [summa-dev/summa-solvency#213]

**Comment by enricobottazzi** [comment]
After benchmarks are ready, to be decided if this will swap the current backend or merged into the current backend. Either way the methods names of the `Round` methods for Polynomial Encoding should match as much as possible the methods of `Round` for Merkle Sum Tree version.

**Comment by sifnoc** [comment]
This issue will close following the merge of https://github.com/summa-dev/summa-solvency/pull/270
