### ISSUE TITLE
Polynomial degree should be known by the verifier without any trust assumption

### ISSUE THREAD

**Issue by enricobottazzi** [summa-dev/summa-solvency#236]
As part of V2, the polynomial degree is used to compute the grandsum.

As you can see from this test https://github.com/summa-dev/summa-solvency/blob/b5d1bcb2c84813d6cffad55c6416c1c24b0904f7/kzg_prover/src/circuits/tests.rs#L195 this can be modified to prove a fake grandsum. Considering the application logic, the prover aims to understate the grandsum of their liabilities. Therefore, the potential attack comes if the prover communicates to the verifier a polynomial degree that leads to an understated grandsum.

Note that the grandsum is a field element obtained as multiplication of two field elements. Therefore is not necessarily true that a smaller polynomial degree leads to an understated grandsum. Indeed, there can be combinations in which a polynomial degree that is higher than the actual one leads to an understated grandsum.

https://github.com/summa-dev/summa-solvency/blob/a81c5f6e6b90112062b5e4692653aba1aac49c70/kzg_prover/src/circuits/utils.rs#L254-L255

We need to find a way for the verifier to verify if the polynomial degree communicated by the prover is correct or not.

**Comment by enricobottazzi** [comment]
The degree of the polynomial is determined by the factor `K` of the circuit. If `K` is set to 17, the degree of the polynomial equals 131072, namely 2**17. The `K` is used by the prover to generate the proving artifacts including the verification key (and the verifier contract, which encodes the verification key)

https://github.com/summa-dev/summa-solvency/blob/a81c5f6e6b90112062b5e4692653aba1aac49c70/zk_prover/src/circuits/tests.rs#L55

In order to solve this issue, the verifier must:
- extract K from the polynomial degree communicated by the Prover as log2(polynomial degree)
- regenerate the verifier contract starting from this K (and the trusted setup provided by the prover) and verify that this matches with the one deployed by the prover.

In production, a script similar to [this](https://github.com/summa-dev/summa-solvency/blob/v2/zk_prover/examples/gen_inclusion_verifier.rs) must be provided to the public.

**Comment by enricobottazzi** [comment]
cc @alxkzmn @sifnoc

**Comment by alxkzmn** [comment]
Awesome!

**Comment by alxkzmn** [comment]
Summary: this means that we need to refactor the smart contract verifier generator to separate the verifier and verifying key. The separate generation is discussed here: https://github.com/privacy-scaling-explorations/halo2-solidity-verifier
Currently, V1 has an example of generating the verifier and the key in the same contract (https://github.com/summa-dev/summa-solvency/blob/master/zk_prover/examples/gen_inclusion_verifier.rs). V2 will need to use separate generation to extract the K by calling extcodecopy(addr, 0x40, 0x60) (check this vk for example https://gist.github.com/han0110/2e7e15b25f25819e85b008d48a47c3fe#file-halo2verifyingkey-sol-L10).

**Comment by alxkzmn** [comment]
Solved in 6ae7b1d28bc46d4dec41f66dbf85f169304315bd
