### ISSUE TITLE
Comparing benchmark between KZG and MST 

### ISSUE THREAD

**Issue by sifnoc** [summa-dev/summa-solvency#240]

**Comment by enricobottazzi** [comment]
To be completed to inform decision on #213 and #244

**Comment by sifnoc** [comment]
This issue is somewhat outdated. For clarity, I've summarized in here:
Although the KZG approach struggles with scalability for larger user bases, such as those around 2^28 users, it remains more efficient for generating inclusion proofs for all user compared to the MST method.

Subsequently, we identified a novel method that significantly reduces the time required to generate all inclusion proofs for users. This new method, an amortized KZG commitment, surpasses the efficiency of the KZG approach in Summa.

Based on these findings, we decided to adopt this new technique. The implementation is applied as per https://github.com/summa-dev/summa-solvency/pull/254
