### ISSUE TITLE
Performance Improvements on user opening

### ISSUE THREAD

**Issue by enricobottazzi** [summa-dev/summa-solvency#243]
The user opening currently takes five times longer than the grand sum opening and I assume this is due to the exponentiation necessary to obtain the user X coordinate. I think it's feasible to maintain a dictionary of pre-calculated powers of $\omega$ against an index and move this calculation outside of the benchmark. This is a new feature so I'll create a separate issue for that if you agree.

_Originally posted by @alxkzmn in https://github.com/summa-dev/summa-solvency/pull/232#pullrequestreview-1790325891_

**Comment by enricobottazzi** [comment]
As we discussed today, an alternative to this approach is just to generate all the opening proofs at once. In the loop generating individual user proof, the power of gamma is just calculated by multiplying the previous powers of gamma by gamma.

**Comment by sifnoc** [comment]
@alxkzmn Do you think this issue is covered with the amortized KZG?

**Comment by alxkzmn** [comment]
Yes, this was solved.
