### ISSUE TITLE
V2 Docs

### ISSUE THREAD

**Issue by enricobottazzi** [summa-dev/summa-solvency#245]
Add reference to: 

#237 
#236 
#235 

Structure of the docs 
1.1 Summa
1.2 Protocol Flow

2.1 Commitments
2.2 zkSNARKs
2.3 Kzg Commitments 
2.4 Univariate Polynomial GrandSum

3.1 Summa Solvency

4.1 UnivariateGrandSum Circuit
4.2 Halo2 Utils 

5.1 Summa.sol Smart Contract

- [x] Add reference to correct release to V1

**Comment by alxkzmn** [comment]
Additional things to mention in the docs:

- [ ] Summa contract deployer should modify the expected zk-proof length in the assertion for the specific circuit configuration (see discussion here: https://github.com/summa-dev/summa-solvency/pull/264/files#r1489028964)

**Comment by sifnoc** [comment]
This can be closed due to release v2 doc on gitbook.
