### ISSUE TITLE
Speed up opening proof

### ISSUE THREAD

**Issue by enricobottazzi** [summa-dev/summa-solvency#247]
It is also important to understand what are the drivers of complexity of the opening proof generation function.

**Comment by alxkzmn** [comment]
The complexity driver of a KZG opening is the quotient polynomial computation. Amortized KZG opening (https://eprint.iacr.org/2023/033) was implemented to speed it up: https://github.com/summa-dev/summa-solvency/blob/fec83a747ead213261aecfaf4a01b43fff9731ee/prover/benches/kzg.rs#L167
Per-user opening performance with the amortized approach is on the order of milliseconds (although memory requirements increase significantly).
