### ISSUE TITLE
Retrieve Poseidon configs from online storage

### ISSUE THREAD

**Issue by alxkzmn** [summa-dev/summa-solvency#35]
The procedure of running python scripts to generate the hasher parameters might be daunting for new users. Instead, we can generate some Poseidon configs for number of assets from 1 to 30, and upload these to an Amazon bucket. The user will just need to download the parameters that matches with their own number of assets, something analogous to when you download a ptau file. 

In that case we might think about adding the file to the .gitignore and keep it for internal use.

_Originally posted by @enricobottazzi in https://github.com/summa-dev/summa-solvency/pull/29#discussion_r1214196590_

**Comment by enricobottazzi** [comment]
Since we are now using a single Poseidon configuration. Can we close this issue @alxkzmn ? 

Also I'm wondering if the python poseidon config generator has to be maintained in the repo any longer
