### ISSUE TITLE
Merkle proof layer region layout refactoring

### ISSUE THREAD

**Issue by alxkzmn** [summa-dev/summa-solvency#37]
If all of the asset balance cells are arranged in a row, the proof size will grow a lot if many assets are added into the tree. For example with proof of solvency with 20 assets, we'd need to create a Poseidon hasher of Rate 42 and Width 43, resulting in 43 advice columns in the zk circuit. 

An optimization that might reduce the dimension of the hasher is to perform a sort of recursive hashing where:

- `l1` is hash_left
- `l2 = H(balance_left_0, balance_left_1, ..., balance_left_19)`
- `r1` is hash_right
- `r2 = H(balance_right_0, balance_right_1, ..., balance_right_19)`

In this way we get to a hasher which maximum dimension is of rate 20 and width 21. If we want to reduce the number of advice even further, we can add even more hashing recursion. 

Additional info => https://hackmd.io/vEhAxFVZRb6TH1QGpokneA

_Originally posted by @enricobottazzi in https://github.com/summa-dev/summa-solvency/pull/29#discussion_r1214200542_

**Comment by enricobottazzi** [comment]
Closing the issue, with the new region layout proposed [here](https://hackmd.io/vEhAxFVZRb6TH1QGpokneA#7-Implement-a-more-verticial-merkle-tree-layer-circuit-design) and implemented [here](https://github.com/summa-dev/summa-solvency/tree/more-efficiency) this should no longer be an issue
