### ISSUE TITLE
Verification `leaf_hash`

### ISSUE THREAD

**Issue by sifnoc** [summa-dev/summa-solvency#64]
Due to PR #51, the user is required to verify `leaf_hash` against balances.

**Comment by enricobottazzi** [comment]
I agree! I guess that verification should be performed within the user-facing API!

**Comment by enricobottazzi** [comment]
@sifnoc I just noticed that verifying the Proof Of Inclusion is not part of the backend (it was just implemented in the CLI). Is it possible to add it?

**Comment by sifnoc** [comment]
Yes, that's certainly feasible. However, I'm unsure about the appropriate place for the inclusion verification step in the snapshot.
What do you think about creating an example for the inclusion verification process in the backend folder?

**Comment by enricobottazzi** [comment]
Good idea!
