### ISSUE TITLE
Fix Poseidon Config

### ISSUE THREAD

**Issue by enricobottazzi** [summa-dev/summa-solvency#66]
As things stand now, the Poseidon Parameters are derived according to the number of assets being supported in the proof of solvency. This is an unnecessary overhead. As part of our effort to make the circuit more efficient and reduce the number of advice columns being used, I propose to fix the Poseidon Config used in our circuit to `WIDTH=3` and `RATE=2`. No matter the number of inputs to the poseidon hasher, the same posiedon config will be used. 

I don't know what's the tradeoff here but it by looking up online, I see that there a few projects such as [ANOMA](https://github.com/anoma/taiga/blob/44380e719ee2d83d23c46ac2dbf63a391b5423a7/taiga_halo2/src/utils.rs#L71) that implement a poseidon with such specifications. 

@sifnoc would you be able to assess the security of such approach? We can also add it as a separate issue with lower priority right now

**Comment by sifnoc** [comment]
> @sifnoc would you be able to assess the security of such approach? We can also add it as a separate issue with lower priority right now

I believe I can assess certain aspects of security with the Poseidon config, specifically with WIDTH=3, RATE=2. However, I won't be able to cover all aspects.
