### ISSUE TITLE
Notice statement for the configuration of overflow chips

### ISSUE THREAD

**Issue by sifnoc** [summa-dev/summa-solvency#70]
Currently, a warning is issued for configurations that don't seem to be set up as intended. 
For instance, if the overflow chip is configured with `MOD_BITS` set to 20 and `MAX_BITS` set to 8, it only utilizes 16 bits. 
We are not sure if this was intentional.

Essentially, the chip checks if `MOD_BITS` is divisible by `MAX_BITS` without a remainder. 
We should make sure to notify the developer or operator about this.

**Comment by enricobottazzi** [comment]
Based on PR #103, the only generic passed to the circuit is `N_BYTES` so there's no longer an issue here

**Comment by sifnoc** [comment]
> Based on PR #103, the only generic passed to the circuit is `N_BYTES` so there's no longer an issue here. I think we can close the issue if #103 gets merged

Agree
