### ISSUE TITLE
Redesign of the LTChip

### ISSUE THREAD

**Issue by enricobottazzi** [summa-dev/summa-solvency#71]
EDIT: number of advice columns in which it should fit from 5 to 3

The current [`LTChip`](https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/main/gadgets/src/less_than.rs) works in a horizontal fashion. 

| lt  | diff[0] | diff[1] | diff[...]    | diff[N_BYTES]        |
| --- | ------- | ------- | --- | --- |
| 1   | 0xff    | 0xff    |  0xff   |  0xff    |

In order to reduce the size of the proof and allows for on-chain verification, we need a more vertical design that fits in 3 advice columns.

Note that the range in which `lhs` and `rhs` lie in our case is 248 BITS. 

How to do that (alternatives):
- [ ] PR the zkevm 
- [ ] Create a new LTChip in summa-solvency
- [ ] Find another existing gadget that works as desired to import

What is part of the issue: 

- Create a vertical LTChip that passes the same testing included here => https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/main/gadgets/src/less_than.rs

What is not part of the issue:

- Integrate the Chip in Summa

**Comment by ameya-deshmukh** [comment]
Hey @enricobottazzi would like to take this up!
