### ISSUE TITLE
Benchmarks are broken

### ISSUE THREAD

**Issue by ec2** [summa-dev/summa-solvency#72]
**Describe the bug**
Hey! I've been trying to run the benchmarks but it seems like the benchmark CSV files are out of date. The benchmarks expect 2 assets whereas the CSV files only give one. In addition, the formatting is wrong for the CSV files as well. I think the deserialization expects `;` for separation and the CSV is comma separated. 

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by enricobottazzi** [comment]
Hi @ec2, thanks for pointing this out. It should be fixed in a day or two. Will update you as soon as this happens.

**Comment by ec2** [comment]
Thanks!!! 🫡

**Comment by enricobottazzi** [comment]
@ec2, benchmark are fixed now. You can test it yourself or have a look at our results here => https://github.com/summa-dev/summa-solvency/tree/master/zk_prover#benchmarking
