### ISSUE TITLE
Further Ideas of improving efficiency of Overflow Check Chip

### ISSUE THREAD

**Issue by enricobottazzi** [summa-dev/summa-solvency#77]
As part of this [PR](https://github.com/summa-dev/summa-solvency/pull/76), a lot of relative rotations were removed. As a consequence of that the performance of the circuit improved drammatically. Proving time went from 1 sec to 250 ms while proving size went from 10k bytes to 2500 bytes. (+75%)

Right now the only remaining area inside our stack that performs a lot of relative rotation is within the ['equality check between decomposed_value and value' gate](https://github.com/summa-dev/summa-solvency/blob/master/zk_prover/src/chips/overflow/overflow_check.rs#L49-L97)

```
                // We are performing an important calculation here to check for overflow in finite field numbers.
                // A single range table is utilized which applies `1 << MAX_BITS` to decompose the column 'b' for range checking.
                //
                // the decomposed values would be represented as follows:
                //
                // |     | a (value)   | b    |
                // |-----|-------------|------|
                // |  0  | 0x1f2f3f    | 0x1f |
                // |  1  |             | 0x2f |
                // |  2  |             | 0x3f |
                //
                // Here, each column `b_n` represents a decomposed value.
                // So, decomposed_value_sum would be calculated as b_0 * 2^16 + b_1 * 2^8 + b_2 * 1
                //
                // During the iteration process in fold, the following would be the values of `acc`:
                // iteration 0: acc = decomposed_value_vec[1] * ( 1 << 8 ) + decomposed_value_vec[2]
                // iteration 1: acc = decomposed_value_vec[0] * ( 1 << 16 ) + decomposed_value_vec[1] * ( 1 << 8 ) + decomposed_value_vec[2]
```

An idea coming from Han is "usually when dealing with large integer range check, we'll try to accumulate chunks by chunks and check the final sum is correct, like this gadget https://github.com/zcash/halo2/blob/main/halo2_gadgets/src/utilities/decompose_running_sum.rs#L55. This might help reduce the rotation usage (it only needs rotation to next row)". 

| row | a (value)  | b(decomposed value) |
| --- | ---------- | ------------------- |
| 0   | 0x1f2f3f4f | -                   |
| 1   | 0x00       | 0x4f                |
| 2   | 0x4f       | 0x3x                |
| 3   | 0x3f4f     | 0x2f                |
| 4   | 0x2f3f4f   | 0x1f                |
| 5   | 0x1f2f3f4f | -                   |

This approach involves modifying the gate a bit. At every row, it would be necessary to check whether 

```
a(cur) + b(cur) * (1 << (i*8)) ) = a(next)
```

Where `a` is the accumulated sum.
Where `i` is 0 at iteration 0.

```
iteration 0: 0x00 + 0x4f * (1<<0) = 0x4f
iteration 1: 0x4f + 0x3f * (1<<8) = 0x3f4f 
iteration 2: 0x3f4f + 0x2f * (1<<16) = 0x2f3f4f 
iteration 3: 0x2f3f4f + 0x1f * (1<<32) = 0x1f2f3f4f 
```

Furthermore a copy constraint must be enforced between the entry value `a_0` and the accumulated value at the end of the iteration `a_5`

### Open Topic

- Note that I move it to little endian, it's just more intuitive to me but not necessary at all 
    - Jin> Might be more efficient with big edian, like 
    
        | row | a (value)  | b(decomposed value) |
        | --- | ---------- | ------------------- |
        | 0   | 0x1f2f3f4f | 0x1f                |
        | 1   | 0x2f3f4f   | 0x2f                |
        | 2   | 0x3f4f     | 0x3f                |
        | 3   | 0x4f       | 0x4f                |
        | 4   | 0x00       |                     |

        ```
        iteration 0: 0x2f3f4f + 0x1f * (1<<32) = 0x1f2f3f4f 
        iteration 1: 0x3f4f + 0x2f * (1<<16) = 0x2f3f4f 
        iteration 2: 0x4f + 0x3f * (1<<8) = 0x3f4f 
        iteration 3: 0x4f + 0x0 = 0x4f 
        ```
        

- Are we missing any constraint here? Is there any security issue here?
    - Jin> I think we should check zero value at a_1, or a_4 (on the big edian case)

### Tradeoff

As tradeoff, this modification will remove one large custom gate of high degree with a set of smaller ones. Furthermore a constant check on the zero value should be added

**Comment by sifnoc** [comment]
Except first iteration, There is one of two overflow checks that is not necessary in this section:

https://github.com/summa-dev/summa-solvency/blob/eee534af6311d89b9c91c36d27f1542bbffa5909/zk_prover/src/circuits/merkle_sum_tree.rs#L236-L252

Above level 1 in the tree, we don't need to check overflow for `current_balance` because it's computed sum above level 1
We only need `leaf_balances` and `path_elements_balances`. so we can achieve with adding condition with `swap_bits` like one below

Above level 1 in the tree, we don't need to check for overflow in `current_balance` because it's a sum of balance above level 1. We only need to check `leaf_balances` and `path_elements_balances`. 

We can achieve this by adding a condition with swap_bits like this:

```Rust
                let mut swap_bit = Fp::zero();
                swap_bit_level.value().copied().map(|x| swap_bit = x);

                if swap_bit == Fp::zero() {
                    overflow_check_chip.assign(
                        layouter.namespace(|| {
                            format!(
                                "{}: asset {}: overflow check next balance",
                                namespace_prefix, asset
                            )
                        }),
                        &right_balance,
                    )?;
                } else {
                    overflow_check_chip.assign(
                        layouter.namespace(|| {
                            format!(
                                "{}: asset {}: overflow check next balance",
                                namespace_prefix, asset
                            )
                        }),
                        &left_balance,
                    )?;
                }
```

This adjustment will eliminate unnecessary overflow checks and could optimize the code.

**Comment by enricobottazzi** [comment]
Hi @sifnoc. I agree with your point on a theoretical level. Indeed if we ensure that `leaf_balances` and `path_elements_balances` are within the desired range of 248 BITS (for example) we also prevent the next balances will never overflow the modulus prime which is 254 BITS. The issue I see with such approach is that we no longer have control over the range of the `computed_sum`. For example, let's consider that we perform the 248 bits range check on `leaf_balances` and `path_elements_balances[0]`. As soon as we sum it together to get `next_balance`, this value can be greater 248 BITS or 249 BITS. This is a problem, for example when using the [`LtChip`](https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/4cfccfa6c3b251284ff61eeb907d548d59206753/gadgets/src/less_than.rs#L29-L38) which requires to specify the range in which `lhs` and `rhs` lie.

Considered so, I would actually suggest to reintroduce the overflow check over the root balances too.

Furthermore, on an implementation level, I don't think if it's technically possible to define conditional circuit assignment as all the polynomial relationship should be known at key generation time (before witness generation)
