### ISSUE TITLE
Implement SummaSigner

### ISSUE THREAD

**Issue by sifnoc** [summa-dev/summa-solvency#83]
To interact with the on-chain verifier, a signer is required in the backend. 
Once PR #79 is merged, we can begin implementing this using `ethers-rs` in the backend.

More specified doc in here https://hackmd.io/0Dp2mudRRCKPov6jI8LYhg?view#Summa-Signer

There are two key features to focus on:
- Signing messages for SignedAccountData
- Sending the submitProofOfSolvency transaction to the on-chain verifier.

**Comment by alxkzmn** [comment]
#99 is in progress.
