### ISSUE TITLE
Resolve using `BigUint` or `BigInt` [LOW PRIO]

### ISSUE THREAD

**Issue by enricobottazzi** [summa-dev/summa-solvency#89]
https://github.com/summa-dev/summa-solvency/blob/482f2790191be9a72ecae21cfb5b8a85757e1834/zk_prover/src/chips/overflow/utils.rs#L4C1-L8C1

It seems like we have a duplicate of the same API here 

https://github.com/summa-dev/summa-solvency/blob/482f2790191be9a72ecae21cfb5b8a85757e1834/zk_prover/src/merkle_sum_tree/utils/operation_helpers.rs#L9

Should we use `BigUint` or `BigInt`?

**Comment by sifnoc** [comment]
> Should we use `BigUint` or `BigInt`?

In the context of the `zk_prover` within the circuit, I believe using `BigUint` would be a slightly better option. 
This could help us avoid accidentally storing a negative number at some point in the future.

**Comment by enricobottazzi** [comment]
Sounds good to me. Can you modify it such that we use a unique converter function?

**Comment by sifnoc** [comment]
Sure I will make it.
