### ISSUE TITLE
Remove unused code and related tests

### ISSUE THREAD

**Issue by enricobottazzi** [summa-dev/summa-solvency#95]
As of now, code related to `ECDSA` and `AggregationCircuit` are not used in the current version. Do you think it's a good idea to remove it from the repo as a whole?

**Comment by sifnoc** [comment]
the tests for Aggregation are ignored since they are too extensive to run with every test. 

Before removing them on master, we could retain these circuits in a new branch. 

This will ensure they're available if we need them in the future.

**Comment by enricobottazzi** [comment]
Good point. I created a new branch based on master as of today => https://github.com/summa-dev/summa-solvency/tree/3-8-aggregation-and-ecdsa
